# Generated by Django 5.0.2 on 2024-04-08 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1200)),
                ('poster', models.URLField(default='https://placehold.co/200x250')),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('show_time', models.CharField(choices=[('11:30', '11:30 AM'), ('14:30', '2:30 PM'), ('17:00', '5:00 PM'), ('21:00', '9:00 PM')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=8, unique=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('seats_booked', models.CharField(max_length=200)),
                ('booking_qr', models.FileField(blank=True, null=True, upload_to='booking_qr/')),
                ('booking_pdf', models.FileField(blank=True, null=True, upload_to='booking_pdfs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.movie')),
            ],
        ),
    ]
