# Generated by Django 5.0.2 on 2024-04-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_bookingregister_selected_show_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingregister',
            name='selected_show_time',
        ),
    ]
